### ISSUE TITLE
No Buffer.from, breaking BrowserFS

### ISSUE THREAD

**Issue by rektide** [jvilk/bfs-buffer#1]
I've grepped through the source a number of times, & scanned around by hand. I can't seem to find any implementation of Buffer.from.

This is particularly relevant because [BrowserFS relies on this function](https://github.com/jvilk/BrowserFS/blob/master/src/generic/key_value_filesystem.ts#L26). I'm initializing a FS with an IndexedDBFileSystem, and after initialization this line is reached & I get a thrown error.

**Comment by jvilk** [comment]
I now recommend using the [standard buffer package](https://github.com/feross/buffer), which BrowserFS typically bundles. `bfs-buffer` is deprecated.

**Comment by rektide** [comment]
What about path & process? Bfs-path & bfs-process, or browserify-path & process?

(Pardon for the close-then-question. FWIW, I'm fine either way, but I want to say I appreciate you having TypeScript implementations from an early age. Even if me and TypeScript don't always get along. :) )

**Comment by jvilk** [comment]
I still use `bfs-path` and `bfs-process` since I support `cwd()` / relative paths, while browserify versions do not. Sorry for the confusion!
